### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'findAll' 

### ISSUE THREAD

**Issue by ghost** [onlyhavecans/ReadItLater-Calibre-Plugin#1]
I am seeing this when I run it on my protected rss feed at readitlater :-

Traceback (most recent call last):
  File "site.py", line 58, in main
  File "site-packages/calibre/ebooks/conversion/cli.py", line 287, in main
  File "site-packages/calibre/ebooks/conversion/plumber.py", line 963, in run
  File "site-packages/calibre/customize/conversion.py", line 208, in **call**
  File "site-packages/calibre/ebooks/conversion/plugins/recipe_input.py", line 105, in convert
  File "site-packages/calibre/web/feeds/news.py", line 861, in download
  File "site-packages/calibre/web/feeds/news.py", line 1005, in build_index
  File "<string>", line 76, in parse_index
AttributeError: 'NoneType' object has no attribute 'findAll'

**Comment by CHIMMARA** [comment]
I have write below code to extract data from Yahoo

but i am getting error message as:AttributeError: 'NoneType' object has no attribute 'findAll'

Can somebody help me please
def save_nifty50_tickers():
    resp=requests.get("https://en.wikipedia.org/wiki/NIFTY_50")
    soup=bs.BeautifulSoup(resp.text)
    table=soup.find("table",{"class":"wikitable sortabe"})
    tickers=[]
    for row in table.findAll("tr")[1:]:
        ticker=row.findAll("td")[0].txt
        tickers.append(ticker)
    with open("nifty50_tickers.picklr","web") as f:
        pickle.dump(tickers,f)
    
    print(tickers)
    
    return tickers

save_nifty50_tickers()
